sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sauce_connect: true
env:
  global:
  - NODE_VERSION=10.5.0
  - secure: KGfm7fTDAPiOhjcycDUMIp311EIWb8jHirTjKWqHWDoTU7A+4KoFM+PwIRV3WpNQaZ2NJkRiWBiPtOPhp1q0snU3Hza/NhUd8vOOOMbT7xGs67AOuAHUZzm1SyinzKLNQ4c1SDuCo7nIA962+pDrBf7hBiDRC0BkYKxPnZ82chvS6weWbsN9D8tI1769v6TRRLWWioqj4ojjsRNO1myVQ5sVzYEMcLypOri66wfuQKv0uCUgitff1uSefGP8TLmx/mAriADtB8pZLrBzrHrdNtnCfdSY4LBxJcuRQCdXCBjmQggj0P5cEFb/wf5tVjPuVWeE3IJXMw0s41A8i0hTCntIOzy6BQZA4NxWNNCfBB43oPnJxt60vrbJSgJOuxr0PXL8GF7WyQEBvLDjyz5+4tJQAsSfo4M6jHIbQb+HVhL4gxBdtMJzWxahXpCyDqnueijfHMGSMu9mq0kA/KTh7CgRqYgSnE9JYCQqOuWBSqGjjKMTK+tLEuhQX9ZP5SpYlWNeWWII32EIWZJl7iypo5qvd/AjAI5s/VDSDblgmSXdqYqQSu94SbChYCrBJ/pnv8JMYPjv4nFsJGY5EKA5acFc+zp4onunKFbCs+BgvsVJolWb2ph24/aBLnOCUJ8MTgm4saVwAourSg/tAkGN0MnQ8MmiP7GyhGykLxWPqrM=
  - secure: M/p4pkAIfFMIkMwUP2iZbh0v9xKss4UBnIEKh0wqYYk4ox0uBLr0WIcJi/+ufnhw4h4EXV4iosJoybhMdZSKoj5QfVSxNtGHoWoHArC9tuS4159EN1Ng/wrJWR/ZGfOdvBD4fLP7QkrQHz9h6s1+m+TfQs+vI97Ks/YjUiDv5H+w+rc48dgO2xBUihZ69fh0w3ivi/86zj8rMAwpfTl4IaGQTXYEiDHiq7lbRnXwSZLa2/rvCUGv4CdMt/exDcDoTVLMX6c5IM8OBv+OWaAyp8yoTjowOLRJfV2RcFISGmigCyaaRbLkXn6h4d+x1ToqaOS7ll2zcda347jfQ5ezePa+mScrc+on16Q9Nwl0qXq5dFv9t5tRDwt80cJzGpGpEL4aWIDldwYO/wX57FhzN7spM7VTnvc+SWkTLmdhagX+hdlX+t9ltnM/tF+rVCnLqzyDvv/I+TIfsoBjNSAIRS8UB/PYcNORb1h8nCqdV+DkjewdjztX+wofKIJ4fuKGBUiSg9KgjikIU5kyI8lj246D5zUKJkQ0EHy73ejubxQ/ZdrkVuSlVtZb94oBdhRwGzbs7lVS7DQ+AVDsCohFkLWffEOjPswmx8CR5KBCGBMdr3LaxsYBkOKbjK92PvGj4yyFBdn0WSx7y67jpesV9KzOtAkjm52Tl2S/hejoqWc=
install:
- nvm install $NODE_VERSION
- npm install -g yarn@1.10.1
- yarn
script:
- yarn run build
- IS_TEST=true yarn run test:quick
- IS_TEST=true yarn run test:e2e:saucelabs
notifications:
  slack:
    rooms:
      secure: fEkSvnWEUVftfjI/lcCLjR/Wk2/vcVXac7v55VWlOIYYOp9/dbpRaH184Yk1nqfrJlECsQzDPcOP2EsBYywDONmsWxKnsWOnyr6hbkvsWDQEhrAmyDE7MLQFEgzRbF/8v3PoKCzGu5n6aK+gBa89CAUjE79pw//rWec2q2gxeeEurK+QUKmzcsjblTzVUOWo/onsq21jZZnk8R71E3HHiJnQAMefhddTr0e8/PNM7BngaiKZThyUdvSn2LH6uDhW+uLpceU28qqVvpgeIz0g97AhXp6rH1+OZizZqQe0yMQXembu/eQt6DligXzoRxxzNj+oH1/04e1UXRJeGh/rx1ExE2NgFDCuCO0YS6/O+yv4MkqwtFPlyKME8REb8z49sOuM7gzSuZxaDL3Ig3xsQr483xLu/2KQvWNs+4kYmVqHTzL6nd4RR7Mok+WYbVqo0Q6TrDcBrdFA2uK8OKikf1NrVgq8f6AWlkU8y/eQ1c2z3p+X2zZjsdUun4UQO9351Gh/R/cm1dg1bIeqhfVG3DRog1OZBdQVAw3E++Q9G+Fds3U+qQA8REDdZIcHT19ZYif54ovZKaME/UF6wdYujOrymjFhFFUY/+lbEgww2ZedRhQAXze3sIcKzjnv6CelenQ0vOGCSSp3joYJDPs7PpPOwfTEZuTWhMpsBJhiFso=
